Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using MO9Project.Models.Validation;
using MO9Project.Models;

namespace MO9Project.Controllers
{
    public class EmployeeController : Controller // sales controller
    {
        private SalesContext context { get; set; } // new property of the context of the db
        public EmployeeController(SalesContext ctx) => context = ctx; // get context from the salescontext db
        
        public IActionResult Index() => RedirectToAction("Index", "Home"); // iactionresult index redirect to the homecontroller index

        [HttpGet] // httpget
        public IActionResult Add() // iaction for the add action
        {
            ViewBag.Employees = context.Employees.OrderBy(e => e.Firstname).ToList(); // viewbag employees get the context of the empoyees
            return View(); // return view
        }

        [HttpPost] // httppost
        public IActionResult Add(Employee employee) // action result for the add action
        {
            // server side checks for remote validation
            string msg = Validate.CheckEmployee(context, employee);
            if (!string.IsNullOrEmpty(msg)) // if the input if null or empty
            {
                ModelState.AddModelError(nameof(Employee.DOB), msg); // model state with the add error
            }
            msg = Validate.CheckManagerEmployeeMatch(context, employee); // message comes from the validate class based on context from the db
            if (!string.IsNullOrEmpty(msg)) // if it's not null or empty
            {
                ModelState.AddModelError(nameof(Employee.ManagerId), msg); // add model error based on the managerid
            }

            if (ModelState.IsValid) // if model state is valid
            {
                context.Employees.Add(employee); // add the employee to the db context
                context.SaveChanges(); // save the changes
                TempData["message"] = $"Employee {employee.Fullname} added"; // add the message with the data added
                return RedirectToAction("Index", "Home"); // redirect back home
            }
            else
            {
                ViewBag.Employees = context.Employees.OrderBy(e => e.Firstname).ToList(); // viewbag of the employees
                return View(); // return that view
            }
        }
    }
}

Controllers/SalesController.cs
using Microsoft.AspNetCore.Mvc;
using MO9Project.Models.Validation;
using MO9Project.Models;

namespace MO9Project.Controllers
{
    public class SalesController : Controller // sales controller
    {
        private SalesContext context { get; set; } // context property based on salescontext
        public SalesController(SalesContext ctx) => context = ctx; // get the context of the db from the salescontext

        public IActionResult Index() => RedirectToAction("Index", "Home"); // iaction result for the index page based on the homecontroller

        [HttpGet] // httpget
        public IActionResult Add() // add iactionresult
        {
            ViewBag.Employees = context.Employees.OrderBy(e => e.Firstname).ToList(); // viewbag the list of employees from the context
            return View(); // return that view
        }

        [HttpPost] // httppost
        public IActionResult Add(Sales sales) // iactionresult add the sales
        {
            // server side check for remote validation
            string msg = Validate.CheckSales(context, sales);
            if (!string.IsNullOrEmpty(msg)) // if it doesnt validate correctly
            {
                ModelState.AddModelError(nameof(sales.EmployeeId), msg); // display the error
            }

            if (ModelState.IsValid) // if modelstate is valid
            {
                context.Sales.Add(sales); // add the sales to the context
                context.SaveChanges(); // save the changes
                TempData["message"] = "Sales added"; // add the data with the message
                return RedirectToAction("Index", "Home"); // redirect to the index home page
            }
            else
            {
                ViewBag.Employees = context.Employees.OrderBy(e => e.Firstname).ToList(); // viewbag employees page to display
                return View(); // return that view
            }

        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MO9Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MO9Project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Add">Add Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sales" asp-action="Add">Add Sales</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>